### ISSUE TITLE
gh-pages

### ISSUE THREAD

**Issue by hut8** [danielcardoso/Load-Awesome#1]
Hey! Thanks so much for these. I plan to use the Pac-Man loader on my new site. I can't believe my luck that you just published these a few hours ago. To preview them I had to clone the repository, which isn't a huge deal, but most other comparable projects have a gh-pages which I didn't see linked to on your README. Would you like me to add that?

**Comment by danielcardoso** [comment]
Hi,
To preview all animations just go to http://github.danielcardoso.net/load-awesome/ :)

Enjoy.
