### ISSUE TITLE
NPM

### ISSUE THREAD

**Issue by mattkoch614** [danielcardoso/Load-Awesome#7]
Any chance you'll be putting this on the npm registry?

**Comment by benbarber** [comment]
+1

**Comment by talesporto** [comment]
+1

**Comment by ZechyW** [comment]
NPM can use this Git repository directly; the following dependencies line in `package.json` works for now:

`"load-awesome": "git://github.com/danielcardoso/load-awesome.git"`

You can then pull the relevant CSS files from `node_modules/load_awesome/css` into your app or project as usual.
